on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: test

jobs:
  setup-r:
    runs-on: ubuntu-16.04
    env:
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/xenial/latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: "3.6"
      - name: Test RSPM
        run: |
          source("https://docs.rstudio.com/rspm/admin/check-user-agent.R")
        shell: Rscript {0}
  rocker:
    runs-on: ubuntu-18.04
    container:
      image: "rocker/rstudio:3.6.3-ubuntu18.04"
    env:
      RSPM: https://packagemanager.rstudio.com/all/__linux__/bionic/latest
    steps:
      - uses: actions/checkout@v2
      - name: Test RSPM
        run: |
          source("https://docs.rstudio.com/rspm/admin/check-user-agent.R")
        shell: Rscript {0}
      - name: Test Install a Binary
        run: |-
          install.packages("remotes", repos = Sys.getenv('RSPM'))
        shell: Rscript {0}
