on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: test

jobs:
  R-CMD-check:
    runs-on: ubuntu-16.04
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/xenial/latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: "3.6"
      - name: Test RSPM
        run: |
          source("https://docs.rstudio.com/rspm/admin/check-user-agent.R")
        shell: Rscript {0}
